### ISSUE TITLE
Unable to build Hercules on Windows 10, missing "zlib.h" file

### ISSUE THREAD

**Issue by jeff-snyder** [wrljet/hercules-helper-windows#1]
Hi Bill,

I'm trying to build the current Hercules on Windows 10, with VS2019.  I've run into an issue I'm hoping you can help me with.

I did a git for hercules-helper-windows today and then ran the following hyperion-buildall command:
```.\hyperion-buildall.ps1 -VS2019 -BuildDir C:\Users\Jeff\Hercules\Software\h220126```

The build falied with: 
```
Makefile presuming VS2019 (VS16 = _MSC_VER 1920)
Target processor type is 64-bit AMD64
msvc.makefile.includes\ZLIB_DIR.msvc(61) : fatal error U1050: ZLIB_DIR "C:\Users\Jeff\Hercules\Software\ZLIB1\include\zlib.h" does not exist. Check ZLIB_DIR
Stop.
makefile.bat ended on Wed 01/26/2022 at 15:29:22.98, rc=2
```
Of course this is unexpected, because the script downloaded ZLIB1-1.2.11-bin-lib-inc-vc2008-x86-x64.zip.  However, when I cancelled the script before at the "Run Tests" step, the Software directory did not have a ZLIB1 subdirectory (or PCRE or BZIP2, for that matter) in it.
```
PS C:\Users\Jeff\Hercules\Software> dir

    Directory: C:\Users\Jeff\Hercules\Software

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         1/26/2022   3:28 PM                h220126
d-----         1/26/2022   3:35 PM                hercules-helper-windows
```
In fact, a search of C:\Users\Jeff\Hercules\Software does not show any ZLIB1 files or directories anywhere.

I'm running Windows 10 Pro, VS2019 and PowerShell 5.1

Some additional PowerShell information:
```
PS C:\Users\Jeff\Hercules\Software\h220126\hyperion> Get-Host

Name             : ConsoleHost
Version          : 5.1.19041.1320
InstanceId       : 716c722b-16ef-4738-94b9-a7971f79f211
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```
Here is the log file that was created:
[hercules-helper-20220126_15-27-50.log](https://github.com/wrljet/hercules-helper-windows/files/7946376/hercules-helper-20220126_15-27-50.log)

Is there any other information I can provide to help resolve this?

**Comment by wrljet** [comment]
Jeff,

The problem appears to be you have environment variables already set before running `hyperion-buildall.ps`
which do not point to the correct locations to which my contraption downloads and unzips them.

- `BZIP2_DIR=C:\Users\Jeff\Hercules\Software\BZIP2`
- `PCRE_DIR=C:\Users\Jeff\Hercules\Software\PCRE`
- `ZLIB_DIR=C:\Users\Jeff\Hercules\Software\ZLIB1`

You should find these packages are in `C:\Users\Jeff\Hercules\Software\h220126\hyperion\winbuild`

As a result, the logic in the Hercules `msvc.makefile.includes` helpers are looking in the wrong place.

I suspect if you unset those three environment variables, it will work correctly.

Bill

**Comment by jeff-snyder** [comment]
That was it.  I never even thought to look at the environment variables, it's probably been over a year since I set them, back when I was figuring out how to build Hercules the old way.  Thanks!

FYI, I cancelled the build script when it said it was going to update my firewall rules.  I run McAfee and I don't think your script would be able to update that.  You might want to consider a -noFirewall switch for people that want to opt-out of these changes or maybe better, a -Firewall switch for people that want to opt-in.

**Comment by wrljet** [comment]
Jeff,

I have added code to check if any pre-existing environment are pointing to the wrong place.
And added a new -Firewall switch as you suggested.  Without it the default is to not add the firewall rules.

Bill

**Comment by jeff-snyder** [comment]
Hi Bill,

I just downloaded and tried the latest buildall script and ran into an issue:

```
C:\Users\Jeff\Hercules\Software\hercules-helper-windows>powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Jeff\Hercules\Software\hercules-helper-windows> .\hyperion-buildall.ps1 -VS2019 -BuildDir C:\Users\Jeff\Hercules\Software\h220207
At C:\Users\Jeff\Hercules\Software\hercules-helper-windows\hyperion-buildall.ps1:268 char:41
+     if ($bzip2_dir_bad || $pcre_dir_bad || $zlib_dir_bad) {
+                                         ~~
The token '||' is not a valid statement separator in this version.
At C:\Users\Jeff\Hercules\Software\hercules-helper-windows\hyperion-buildall.ps1:268 char:24
+     if ($bzip2_dir_bad || $pcre_dir_bad || $zlib_dir_bad) {
+                        ~~
The token '||' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : InvalidEndOfLine

PS C:\Users\Jeff\Hercules\Software\hercules-helper-windows> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\Users\Jeff\Hercules\Software\hercules-helper-windows>
```

Maybe a higher level of PowerShell is required now?  This is on Windows 10 Pro, using the "built in" PowerShell.

**Comment by wrljet** [comment]
Jeff,

Hmm, I ran into that too, during development work and corrected it.
Perhaps it didn't get checked in.

I will look at it, fix, and let you know.

Bill

**Comment by wrljet** [comment]
OK, should be fixed now with commit https://github.com/wrljet/hercules-helper-windows/commit/8565e6ebc750c220b9d2632feeed97842423b981

**Comment by jeff-snyder** [comment]
Thanks, that fixed it.
