### ISSUE TITLE
Building Hercules with Hercules-Helper

### ISSUE THREAD

**Issue by PatGitHub01** [wrljet/hercules-helper-windows#10]
I try to perform a complete build of Hercules by executing the script .\hercules-buildall.ps1 -VS2017 -BuildDir c:\hercules -Flavor Aethra 
I get this error : the process is freezing in Starting Hercules-Step 2 (as follow)
![image](https://github.com/user-attachments/assets/467b1bb2-7b4b-427f-a26f-abc6c6ecde22)
Nothing happens when I press enter.
I tried with Windows 11 but also with Windows Server 2022 : same result as a same stage

Second attempt: I restarted the process (.\hercules-buildall.ps1 -VS2022 -BuildDir c:\hercules -Flavor Aethra on Windows 11) but I had installed VSCode 2022 on my PC before launching the script. 
After almost 1 hour, I was still stuck at the same point as before so I cancelled the script and take the log file 
[hercules-helper-20240929_19-48-50.zip](https://github.com/user-attachments/files/17186510/hercules-helper-20240929_19-48-50.zip)

Thanks for your help

Patrick

**Comment by PatGitHub01** [comment]
Hello,
I tested the same script (.\hercules-buildall.ps1 -VS2022 -BuildDir c:\hercules -Flavor Aethra) but, this time, with the English Windows 2022 Server (in order to prevent French character set issue) and the result was the same at the same stage.
[hercules-helper-20240930_09-32-44.zip](https://github.com/user-attachments/files/17194149/hercules-helper-20240930_09-32-44.zip)
Regards

**Comment by wrljet** [comment]
We'll get it figured out.

**Comment by PatGitHub01** [comment]
These issue is solved.
I did not used the right PowerShell version !!! 
Due to the fact, I used either latest Windows 11 and Windows Server 2022 version, I was certain to use the latest PowerShell version, I was false.
By typing the version PowerShell command: Get-Host | Select-Object Version I noticed I used PowerShell V5 ☹
So, I downloaded the latest PowerShell version (7.5) and … the script has unlocked and Hercules emulator has been build. 
I’m very confused because the README.md included in the Hercules-Helper package mentioned very clearly:  You will need a modern version of PowerShell, such as version 7.x.
Thnaks for your help.
Patrick

**Comment by wrljet** [comment]
That was going to be my next suggestion, although it works fine for me with PS 5.1.

I did notice you were running under PowerShell ISE (I don't even know what that is), and I wonder if that was the reason.

Bill

**Comment by PatGitHub01** [comment]
Hi Bill, 

 

I will test with PowerShell v5.1 without ISE. 

 

I keep you inform.

 

Patrick

 

De : Bill Lewis ***@***.***> 
Envoyé : mardi 1 octobre 2024 17:10
À : wrljet/hercules-helper-windows ***@***.***>
Cc : PatGitHub01 ***@***.***>; State change ***@***.***>
Objet : Re: [wrljet/hercules-helper-windows] Building Hercules with Hercules-Helper (Issue #10)

 

That was going to be my next suggestion, although it works fine for me with PS 5.1.

I did notice you were running under PowerShell ISE (I don't even know what that is), and I wonder if that was the reason.

Bill
