### ISSUE TITLE
Warning C4789 treated as error - Link fails

### ISSUE THREAD

**Issue by vbandke** [wrljet/hercules-helper-windows#12]
I have been building hercules with the splendid hercules-helper-windows quite a few times now, with no issues.  But today, when trying to get the latest and greatest hercules version, I run 

`.\hercules-buildall.ps1 -VS2022 -BuildDir D:\UTI -Flavor SDL-Hyperion -GitBranch develop
`

from my unchanged (!) hercules.helper directory and got

```
D:\Uti\sdl-hyperion\general1.c(2269) : error C2220: the following warning is treated as an error
D:\Uti\sdl-hyperion\general1.c(2269) : warning C4789: in function 'z900_compare_and_form_codeword' buffer 'tmp' of size 16 bytes will be overrun; 16 bytes will be written starting at offset 16
D:\Uti\sdl-hyperion\general1.c(2240) : warning C4789: in function 'z900_compare_and_form_codeword' buffer 'tmp' of size 16 bytes will be overrun; 16 bytes will be written starting at offset 16
LINK : fatal error LNK1257: code generation failed
```
I did see that warning on earlier builds. but they were not converted to errors then.  Probably this is error 30  ("The error is 30 inches in front of the screen").  What am I overlooking/doing incorrectly/having misunderstoood?

With best regards
Volker Bandke

**Comment by wrljet** [comment]
Volker,

Hmm... "It works for me" (tm)

This has come up a few times recently as MSVC releases seem to be getting more annoying with their incorrect warnings.
We have made changes to SDL-Hercules, as you noticed, to try to keep up with it, but it is a moving target.

Please try adding the `-ForceClone` switch to your command line, just to make sure you have the latest of those changes.
**_Note, this will override your git repo and blow away any local changes._**

If that doesn't fix it, please send me the hercules-helper log file so I can compare MSVC version with what I have here.
I seem to be running MSVC 2022 17.11.2.  There is a slightly newer 17.11.5.  But I'd like to hear back before I update to that version.

Thanks,
Bill

**Comment by albrecht-kroll** [comment]
Hello,
i have the same issue. I tried the rebuild with -ForceClone switch. 
The makefile.bat ended on 26.11.2024 at 14:56:01,03, rc=2
Attachment
[hercules-helper-20241126_14-48-57.log](https://github.com/user-attachments/files/17923782/hercules-helper-20241126_14-48-57.log)

**Comment by albrecht-kroll** [comment]
There are no executables in the msvc.AMD64.bin directory.

Thanks Albrecht

**Comment by vbandke** [comment]
***Note:  This is a copy of a reply I sent 3 weeks ago vie e-mail.  Just to complete this issue ***


Hello Bill, 

Many Thanks for your quick (and very helpful) reply :)

I did not know about the -ForceClone switch, and thus started all over - i.e. I renamed the old target directory, also the old hercules-helper directory, got a new clone of hercules-helper and had that new hercules-helper then do its thing.  It downloaded an updated version of MSVC (Visual Studio 2022 Developer Command Prompt v17.11.5) and everything worked nicely from there on.  Issue can be closed :)

With best regards from Germany


Volker

**Comment by wrljet** [comment]
Albrecht,

> Hello, i have the same issue. I tried the rebuild with -ForceClone switch. The makefile.bat ended on 26.11.2024 at 14:56:01,03, rc=2 Attachment [hercules-helper-20241126_14-48-57.log](https://github.com/user-attachments/files/17923782/hercules-helper-20241126_14-48-57.log)

You need to add the `-GitBranch=develop` command line switch.  This will get you the latest code from the Hercules repo, which has fixes for this problem:

```
E:\hercules2022\aethra\general1.c(2269) : error C2220: Die folgende Warnung wird als Fehler behandelt.
E:\hercules2022\aethra\general1.c(2269) : warning C4789: In Funktion "z900_compare_and_form_codeword" wird der Puffer "tmp" mit der Größe von 16 Bytes überlaufen; 16 Bytes werden ab Offset 16 geschrieben.
```

Bill

**Comment by albrecht-kroll** [comment]
Hello Bill,
it works with the switch -GitBranch develop. Thanks Albrecht
