### ISSUE TITLE
No hercules.cnf file Created

### ISSUE THREAD

**Issue by ITENETI** [wrljet/hercules-helper-windows#15]
Hello!

I ran the hercules-buildall.ps1 script to build Hercules using Hercules Helper, and the process completed successfully according to the tests and logs. However, I encountered two issues:

After the build process, PowerShell remains open, and no DOS/Command Prompt is launched automatically.
When I try to manually start hercules.exe, I get the following error:

Configuration file 'hercules.cnf' not found: No such file or directory

The logs indicate that everything passed without any errors, but when I attempt to run Hercules manually, the missing configuration file prevents it from starting. I am unsure whether the hercules.cnf file is supposed to be generated automatically or if I need to create it manually, and if so, what the default content should be.

Please let me know if I should attach the logs for further troubleshooting.

Environment:

OS: Windows 10 (64-bit)
PowerShell Version: 7.x
Hercules Version: Hercules Aethra 4.6.0
Visual Studio: 2022
Thanks so much

**Comment by wrljet** [comment]
Hi

There is a default / sample `hercules.cnf` in the source code directory.

But in general to use Hercules you're going to need to craft your own config (probably using that example as a starting point).

Documentation on the config may be found [here](https://sdl-hercules-390.github.io/html/hercconf.html)

Help with operating Hercules is discussed on this [mailing list](https://hercules-390.groups.io/g/group)

Bill

**Comment by ITENETI** [comment]
> Hi
> 
> There is a default / sample `hercules.cnf` in the source code directory.
> 
> But in general to use Hercules you're going to need to craft your own config (probably using that example as a starting point).
> 
> Documentation on the config may be found [here](https://sdl-hercules-390.github.io/html/hercconf.html)
> 
> Help with operating Hercules is discussed on this [mailing list](https://hercules-390.groups.io/g/group)
> 
> Bill

Thanks so much!

**Comment by wrljet** [comment]
Have you gotten further?
