### ISSUE TITLE
How to build a specific commit in Windows

### ISSUE THREAD

**Issue by jeff-snyder** [wrljet/hercules-helper-windows#2]
Hi Bill,

I need to build a specific commit of Hercules in Windows.  I see there is a "-GitBranch" flag on the buildall script, is there also something like a "-GitCommit" available?  If not, is there a configuration file I can edit like in the non-Windows Hercules-Helper to tell it what commit to get?

Thanks for these tools, by the way, they make this stuff a lot easier!

Jeff Snyder

**Comment by wrljet** [comment]
Jeff,

The answer was "no", but I just added it for you.
New `-GitCommit` optional parameter.

For example, add to the command line: `-GitCommit f6f1e51`

Bill

**Comment by jeff-snyder** [comment]
Thanks, this worked liked a charm!
