### ISSUE TITLE
Typo in published README.md build instructions

### ISSUE THREAD

**Issue by Fish-Git** [wrljet/hercules-helper-windows#4]
> _**Step 4:**_
>
> [...]
> 
> If the -GitBranch option is specified, a branch other than master may be checked-out. Such as:
> 
> `.\hercules-buildall.ps1 -VS2017 -BuildDir c:\hercules Flavor SDL-Hyperion -GitBranch develop`

You're missing the '-' on the `Flavor` option. It _should_ be:

<pre>
.\hercules-buildall.ps1 -VS2017 -BuildDir c:\hercules <b><i>-Flavor</i></b> SDL-Hyperion -GitBranch develop
</pre>

**Comment by wrljet** [comment]
Thanks, Fish.

Fixed with commit https://github.com/wrljet/hercules-helper-windows/commit/5ebabc9dd90ae4fb550777c62155063ddb484401
