### ISSUE TITLE
Set-ExecutionPolicy RemoteSigned not working - Unrestricted works

### ISSUE THREAD

**Issue by wrljet** [wrljet/hercules-helper-windows#6]
arfineman reports:

Hi Bill,
Thank you for putting this together. It is a life saver for computer illiterates like me. I was able to do a build about a year ago on Windows 10 and was successful. But I tried to build a new one on the same PC and it did not work. After setting the execution-policy to remotesigned, I still got a message from PowerShell it it would not load the Hyperion-Buildall because it is not digitally signed. However, after doing some google searches, I set it to 'unrestricted' and it worked. I thought you may want to mention that in the instructions.
My question now is that if I want to make a modification to one of the .c modules and recompile, how can I do that ? If at all possible.
Best regards,

**Comment by wrljet** [comment]
Aaron,

I think you might have missed this snippet in the instructions:

```
Sometimes when files are copied to Windows, it will decide they have come from an untrusted remote system,
and a directory bit will be set to remember this fact. This will cause Windows to not allow them to be executed.

Right-click on the hercules-helper.zip file and select Properties. At the bottom ofthe Properties dialog, 
you may see a warning about the file coming from a remote system. Click the button to Unblock the file. 
Close this dialog.
```

If you do this I doubt you'll need `unrestricted`, which is more dangerous.

To answer your other question...  `hercules-buildall.ps1` creates a DOS batch file called `rebuild.cmd`.
Run that from a DOS command prompt and it'll redo just the compile part of the process for you.

You should examine it before running to verify the paths, etc. are what you want.

Bill

**Comment by arfineman** [comment]
Thanks so much, Bill.
This worked great. I was actually able to use your instructions and update my Windows 7 PowerShell and do the build on my Windows 7.
Best regards,

**Comment by wrljet** [comment]
Great!  I'm glad it all worked for you.

Bill
