### ISSUE TITLE
RUNTEST.CMD fails in non-English based Windows system

### ISSUE THREAD

**Issue by vbandke** [wrljet/hercules-helper-windows#7]
Hercules-Helper fails after building when trying to run the "runtest.cmd" batch file.   runtest.cmd  creates a temporary file from the current date/time of the system, and places corresponding info into that temp file.

Unfortunately, it uses the incorrect delimiters when scanning/parsing the date/time.  In a German based windows system the date looks like this

`07.01.2024`   (which is January 7, 2024, and uses a dot as seperator, not a slash

The time, otoh, look like this

`14:14:32,79`   (which uses colon between hh, mm and ss, and a decimal comma insted of a decimal point)

Because of this the generated REXX file fails already on the PARSE statement in line 1.

```
  PARSE ARG '"' formula '"'     ,2518820.rexx
  INTERPRET 'mttof = 'formula   ,2518820.rexx
  SAY FORMAT(mttof,,1)          ,2518820.rexx

```

With best regards

Volker Bandke

**Comment by vbandke** [comment]
I don't understand any of the build processes, and thus cannot say if the issue(s) reported havwe there cause in the hercules-helper package or in the actual hercules code.  The issue happens when trying to build both supported flavours of Hercules, and thus I assumed the issue is in the common denominator, the hercules-helper.   This assumption might be wrong, of course, and I apologize in advance for bothering.

With best regards

Volker Bandke

**Comment by wrljet** [comment]
Volker,

Not a bug in Hercules-Helper.
I will address this over on the Hercules repos.

Bill
